language: python

python:
  - "2.7"

branches:
  only:
    - master

# command to install requirements
install:
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - python ./libcnml/tests/test_libcnml.py && pip install lxml && python ./libcnml/tests/test_libcnml.py
